#ifndef ERRORMESSAGE_PRJ_H_INCLUDED
#define ERRORMESSAGE_PRJ_H_INCLUDED

#define ERROR_BUF_SIZE 4

#define ERROR_MESSAGE_LIST \
   ERROR_MESSAGE_ENTRY(TESTERROR, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(SHUNTCOMM, ERROR_STOP)
#endif // ERRORMESSAGE_PRJ_H_INCLUDED
